## ASSIGNMENT 3

In [5]:
import numpy as np

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [6]:
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [20]:
list1=np.array([int(input()) for i in range(5)])
list2=np.array([int(input()) for i in range(5)])
print(np.concatenate([list1,list2]))
print(np.sort(np.concatenate([list1,list2])))

5
4
3
2
1
9
8
7
6
5
[5 4 3 2 1 9 8 7 6 5]
[1 2 3 4 5 5 6 7 8 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
print(arr.size)

2
9


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [54]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.expand_dims(arr,2))


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [31]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Questions 6:
How to get unique items and counts of unique items?

In [35]:
arr=np.array([9,2,4,2,4,6,8,1,2,3,4,5,8,9])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([1, 3, 1, 3, 1, 1, 2, 2], dtype=int64))
